name: Auto Post Video to Facebook

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:        # allows manual trigger

jobs:
  post-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Facebook video post script
        env:
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
        run: node index.js
